### ISSUE TITLE
Accounts?

### ISSUE THREAD

**Issue by 4X1513X** [Shaveyy/TwitchSpam#22]
How to create accounts? tutorial pls

**Comment by Shaveyy** [comment]
* Create an account on twitch.tv

* Open the chrome console with the shortcut CTRL + SHIFT + J

* Once it's open enter this code into the console

```
function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}

var token = getCookie("auth-token")
console.log("\n\n\n\nCODE TO PASTE IN DISCORD:\n!donateoauth oauth:" + token + "\n\n\n\n")
```

* Then follow the instructions in the output

**Comment by Shaveyy** [comment]
Closing this...  Reopen if the issue persists
