### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by qmadryx** [Shaveyy/TwitchSpam#54]
Hi , my commands are not working . 
![image](https://user-images.githubusercontent.com/41635972/115193014-467d1900-a0f4-11eb-8bdd-5dd26e63a6b0.png)

**Comment by Shaveyy** [comment]
I have addressed in commit 79b042f863cd9d414953b29bce4ac35b35556ead. Hopefully, this addresses your issue, no guarantees though as I work from a primarily Linux environment.
