### ISSUE TITLE
Suggestion: Be Able to Choose Shocker For BBC Stream

### ISSUE THREAD

**Issue by Flusak1235** [Shaveyy/TwitchSpam#6]
just a cool little suggestion, title says it all.

**Comment by Shaveyy** [comment]
## Idea
Splice in video clips using [moviepy](https://pypi.org/project/moviepy/). Since I don't wanna break GitHub TOS, the videos will have to be uploaded.
The general idea is that you'd be able to put a clip in the start, end and middle
