### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by C0DE4ME** [Shaveyy/TwitchSpam#70]
A way to see if old !donateoauth's are still valid or not would be helpful, for example:
!followbot returns: "Finished following XXXX with X accounts. This means XX of our accounts are banned :hacker:"
So the codes logic is aware that some of the oauth token's are out of commission but it cant show or self fix the specific oauth token's.
A new command or likewise to check the oauth token's validity would be nice.

Other than that this project is god tier ty!

**Comment by Shaveyy** [comment]
Addressed in commit 134fd9d1f853b27de17608edc5aba3c704333556. I originally had code that would check this, but it ended up getting discarded due to Twitch migrating to a new API.

**Comment by C0DE4ME** [comment]
You will be happy to hear after some testing this works perfectly ty!
This helps so much ty.
